// src/assets/Input.vue
<template>
    <div>
        <div id="buttons">
            <button @click="addCase()">Add Case (Ctrl+G)</button>
            <button @click="saveCases()">Save Cases (Ctrl+S)</button>
            <button @click="resetCases()" class="danger">Reset Cases</button>
        </div>
        <div>
            <div v-for="(testCase, index) in cases" :key="index">
                <h3>
                    Case #{{ index + 1 }}
                    <button @click="removeCase(index)" class="btn-sm">X</button>
                    <button @click="insertCaseAbove(index)" class="btn-sm">^</button>
                </h3>

                <table>
                    <col width="10em">
                    <col width="100%">

                    <tr>
                        <td>
                            Input:
                            <div v-if="!testCase.input">(Empty)</div>
                        </td>
                        <td>
                            <div>
                                <textarea :name="`input${index}`" :id="`input${index}`" :rows="rowReq(testCase.input)" v-model="testCase.input"></textarea>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Output:
                            <div v-if="!testCase.output">(Empty)</div>
                        </td>
                        <td>
                            <textarea :name="`output${index}`" :id="`output${index}`" :rows="rowReq(testCase.output)" v-model="testCase.output"></textarea>
                        </td>
                    </tr>
                </table>

                <!-- <p>{{ JSON.stringify(testCase) }}</p> -->
            </div>
        </div>
    </div>
</template>

<script>

export default {
    name: 'CaseData',
    data() {
        return {
            cases: []
        }
    },
    methods: {
        /**
         * Adds a new empty case
         */
        addCase() {
            this.cases.push({
                input: '',
                output: ''
            });
        },

        /**
         * Sends the cases back to main (the extension)
         */
        saveCases() {
            EventBus.$emit(EventTypes.PostEventToMain, 'inputOutput', {
                type: 'setCases',
                event: this.cases
            });
        },

        /**
         * Resets (deletes) all cases
         */
        resetCases() {
            this.cases = [];
            EventBus.$emit(EventTypes.PostEventToMain, 'inputOutput', {
                type: 'resetCases',
                event: undefined
            });
        },

        /**
         * Removes the case with the specified index
         * @param index Index to remove
         */
        removeCase(index) {
            this.cases.splice(index, 1);
        },

        /**
         * Inserts an empty case above the specified index
         * @param index Index to insert at
         */
        insertCaseAbove(index) {
            this.cases.splice(index, 0, {
                input: '',
                output: ''
            });
        },

        /**
         * Sends a "ready" signal to the extension
         */
        sendReadySignal() {
            EventBus.$emit(EventTypes.PostEventToMain, 'inputOutput', {
                type: 'ready',
                event: undefined
            });
        },

        /**
         * Number of lines required for the text area given the current text
         * Currently set to (No. Of Lines + 1)
         */
        rowReq(input) {
            let cnt = 1;
            for (const ch of input)
                cnt += ch === '\n';
            return Math.max(cnt, 2);
        }
    },
    mounted() {
        this._keyListener = function(e) {
            if (e.ctrlKey || e.metaKey) {
                if (e.key === 'g') { // Add new case
                    e.preventDefault(); // prevent "Save Page" from getting triggered.
                    this.addCase();
                }
                else if (e.key === 's') { // Save cases
                    e.preventDefault(); // prevent "Save Page" from getting triggered.
                    this.saveCases();
                }
            }
        };

        document.addEventListener('keydown', this._keyListener.bind(this));

        // Listen for events
        EventBus.$on('inputOutput', event => {
            // console.log('IOE: ' + JSON.stringify(event));
            if (event.type === 'setCases') { // setCases from extension
                this.cases = event.event;
            }
        });
    },
    beforeDestroy() {
        document.removeEventListener('keydown', this._keyListener);
    }
}
</script>

<style lang="scss" scoped>

@import 'scss/global.scss';
@import 'scss/main.scss';

textarea {
    box-sizing: border-box;
    resize: none;
    width: 100%;
}

table {
    width: 100%;
}

#buttons {
    margin-bottom: 20px;
}

h3 {
    color: map-get($theme, 5);
    margin-top: 10px;
    margin-bottom: 2px;
}

td {
    color: $text-color;
}

</style>

// src/assets/input.jsx
import React from 'react';
import ReactDOM from 'react-dom';
import EventBus from './vscodeEventBus';
 
// Key code constants
const ENTER = 13, R = 82, S = 83;

class InputDisplay extends React.Component {
    constructor(props) {
        super(props);

        // Initialize state
        this.state = {
            // Command State info
            curCommand: '',
            lastCommandOutput: null,

            // Current test set being viewed state info
            curTestSet: null,
            curTestIndex: null,
            curTestInput: null,
            curTestOutput: null,

            // Test cases
            cases: []
        };
        
        // Initialize other event handlers
        EventBus.on('caseCommand', resp => {
            if (resp.length > 0)
                this.setState({ lastCommandOutput: resp });
        });
        EventBus.on('updateAll', cases => {
            this.setState({ cases });
            if (this.state.curTestIndex !== null) // Refresh current open test case
                this.selectTestCase(this.state.curTestIndex);
        });
        EventBus.on('updateStructure', _ => { throw new Error('Not implemented yet (defunct)'); });
        EventBus.on('updateCase', caseUpdate => {
            const casesObj = this.state.cases;
            casesObj[caseUpdate.key][caseUpdate.index][caseUpdate.isInput ? 'input' : 'output'] = caseUpdate.newData;
        });

        // Add key listener
        this._keyListener = function(e) {
            if (e.keyCode === ENTER) // user pressed enter
                this.dispatchCommand();
            if (e.ctrlKey && e.keyCode === S) // user pressed Ctrl+S, Save current case 
                this.saveCurTestCase();
            if (e.ctrlKey && e.keyCode === R) // user pressed Ctrl+R, Refresh all cases
                EventBus.post('updateAll');
        };
        document.addEventListener('keydown', this._keyListener.bind(this));

        // We're ready!
        EventBus.post('updateAll');
    }

    componentWillUnmount() {
        document.removeEventListener('keydown', this._keyListener);
    }

    /**
     * Sends a command back to the extension host
     */
    dispatchCommand() {
        if (this.state.curCommand.length === 0) return; // Empty command
        EventBus.post('caseCommand', this.state.curCommand);
        this.setState({ curCommand: '' });
    }

    /**
     * Selects a test set (for viewing/editing)
     * @param {string} testSetName The name of the test set to select (assumed valud)
     */
    selectTestSet(testSetName) {
        this.setState({ 
            curTestSet: testSetName,
            curTestIndex: this.state.cases[testSetName].length > 0 ? 0 : -1
        });
    }

    /**
     * Selects a test case (for viewing/editing)
     * @param {string} index The index of the test case to select
     */
    selectTestCase(index) {
        this.setState({
            curTestIndex: index,
            curTestInput: this.state.cases[this.state.curTestSet][index].input,
            curTestOutput: this.state.cases[this.state.curTestSet][index].output,
        });
    }

    /**
     * Save the data of the current edited test case
     */
    saveCurTestCase() {

    }

    render() {
        return (
            <div>
                <h1>Test Cases</h1>
                <a href="#" onClick={() => EventBus.post('updateAll')}>Refresh</a>

                {/* Command input/output */}
                <input id="commandInput" placeholder="Type a command here..." value={this.state.curCommand} onChange={e => this.setState({ curCommand: e.target.value })}></input>
                <button onClick={this.dispatchCommand()}></button>

                { this.state.lastCommandOutput === null ? (null) :
                    <p>{this.state.lastCommandOutput}</p>
                }

                {/* Display status of current test set and test case selection menu */}
                { this.state.curTestSet === null ? (null) :
                    <React.Fragment>
                        <table>
                            <col width="10em" />
                            <col width="100%" />

                            <tr>
                                <th>Case</th>
                                <th>On/Off</th>
                                <th>Edit Input</th>
                                <th>Edit Output</th>
                            </tr>
                            { this.state.cases[this.state.curTestSet].map((testCase) => 
                                <tr key={testCase.index}>
                                    <td>{testCase.index}</td>
                                    <td>{testCase.disabled ? 'Disabled' : 'Not Disabled'}</td>
                                    <td><a href="#" onClick={() => EventBus.post('openCaseFile', { key: this.state.curTestSet, index: testCase.index, isInput: true })}>Edit</a></td>
                                    <td><a href="#" onClick={() => EventBus.post('openCaseFile', { key: this.state.curTestSet, index: testCase.index, isInput: false })}>Edit</a></td>
                                </tr>
                            )}
                        </table>

                        <h2>Test Sets</h2>
                        <ul>
                            { Object.keys(this.state.cases).map(testSetName => 
                                <li key={testSetName}>
                                    <a href="#" onClick={() => this.selectTestSet(testSetName)}>{testSetName}</a>
                                </li>
                            )}
                        </ul>
                    </React.Fragment>
                }

                {/* Select Test Case to Edit */}
                { this.state.curTestIndex === null ? (null) :
                    <div>
                        <span>Test Cases: </span>
                        { this.state.cases[this.state.curTestSet].map((_, index) =>
                            <a href="#" key={index} onClick={() => this.selectTestCase(index)}>{index}</a>
                        )}
                    </div>
                }

                {/* Edit Test Cases */}
                <div>
                    <div>

                    </div>
                    <div>

                    </div>
                </div>
                <button onClick={this.saveCurTestCase}>Save</button>
            </div>
        );
    }
}

{/*
<style lang="scss" scoped>

@import 'scss/global.scss';
@import 'scss/main.scss';

textarea {
    box-sizing: border-box;
    resize: none;
    width: 100%;
}

table {
    width: 100%;
}

#buttons {
    margin-bottom: 20px;
}

h3 {
    color: map-get($theme, 5);
    margin-top: 10px;
    margin-bottom: 2px;
}

td {
    color: $text-color;
}

</style>*/}

let App = document.getElementById('App');
ReactDOM.render(<InputDisplay />, App);
